<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoverLetterAI.Service\CoverLetterAI.Service.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Vbe.Interop">
			<HintPath>..\..\..\..\..\..\Windows\assembly\GAC_MSIL\Microsoft.Vbe.Interop\15.0.0.0__71e9bce111e9429c\Microsoft.Vbe.Interop.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="office">
			<HintPath>..\..\..\..\..\..\Windows\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\OFFICE.DLL</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
</Project>
